#!/bin/bash
# This is a tool which allows systemd to send a mail.
# Based on the original solution taken from
#  https://wiki.archlinux.org/index.php/Systemd/Timers#MAILTO
#
# It expects these parameters:
# $1: the recipient of the mail
# $2: the service name

SENDMAIL=$(/usr/bin/which sendmail)
DOMAIN=example.com
FROM=postmaster@$DOMAIN
MessageID=$(date +%s | sha256sum | base64 | head -c 32)@$DOMAIN

$SENDMAIL -f $FROM -t <<ERRMAIL
From: "$HOSTNAME Systemd" <$FROM>
To: "Sysadmin" <$1>
Subject: Important notice about "$2"
Message-ID: <$MessageID>
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=UTF-8

Hello,

 I'm the Systemd of $HOSTNAME and I want let you know something about
a service named "$2".
Please, read the following details.

$(systemctl status --full "$2")
ERRMAIL
