GRANT USAGE ON `miltermap` . * TO 'blackuser'@'localhost' IDENTIFIED BY PASSWORD '*2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

GRANT SELECT , 
INSERT ,
UPDATE ,
DELETE ,
LOCK TABLES ON `miltermap` . * TO 'blackuser'@'localhost';

GRANT USAGE ON `milteripmap` . * TO 'blackuser'@'localhost' IDENTIFIED BY PASSWORD '*2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

GRANT SELECT ,
INSERT ,
UPDATE ,
DELETE ,
LOCK TABLES ON `milteripmap` . * TO 'blackuser'@'localhost';
